name:                corecursive-main
version:             0.1.0.1
github:              "lucasdicioccio/corecursive-main"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018 Lucas DiCioccio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Write your main like it can call itself back.
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lucasdicioccio/corecursive-main#readme>

dependencies:
- base >= 4.7 && < 5
- async
- process
- text
- distributed-closure
- base64-bytestring
- binary
- bytestring

library:
  source-dirs: src

executables:
  corecursive-main-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corecursive-main
    - unix

tests:
  corecursive-main-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corecursive-main
